jeonsein/KH_FinalProject

src/main/java/org/zerock/myapp/controller/LoginController.java

[셍나는 충돌을 해결 중 -ㅇ- ]

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/java/org/zerock/myapp/domain/LoginDTO.java

[셍나] 로그인 컨트롤러 수정

---

src/main/java/org/zerock/myapp/controller/AdminController.java
src/main/java/org/zerock/myapp/controller/NoticeController.java
src/main/java/org/zerock/myapp/domain/ProductDTO.java
src/main/java/org/zerock/myapp/domain/ProductVO.java
src/main/java/org/zerock/myapp/mapper/FarmMapper.java
src/main/java/org/zerock/myapp/mapper/NoticeMapper.java
src/main/java/org/zerock/myapp/mapper/ProductMapper.java
src/main/java/org/zerock/myapp/service/FarmService.java
src/main/java/org/zerock/myapp/service/ProductService.java
src/main/java/org/zerock/myapp/service/ProductServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/FarmMapper.xml
src/main/resources/org/zerock/myapp/mapper/NoticeMapper.xml
src/main/resources/org/zerock/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/admin/farm/list.jsp
src/main/webapp/WEB-INF/views/admin/notice/list.jsp
src/main/webapp/WEB-INF/views/admin/product/get.jsp
src/main/webapp/WEB-INF/views/admin/product/list.jsp
src/main/webapp/WEB-INF/views/admin/product/modify.jsp
src/main/webapp/WEB-INF/views/admin/product/register.jsp
src/test/java/org/zerock/myapp/controller/AdminControllerTests.java
src/test/java/org/zerock/myapp/controller/FaqControllerTests.java
src/test/java/org/zerock/myapp/controller/FarmControllerTests.java
src/test/java/org/zerock/myapp/controller/NoticeControllerTests.java
src/test/java/org/zerock/myapp/mapper/NoticeMapperTests.java
src/test/java/org/zerock/myapp/mapper/ProductMapperTests.java
src/test/java/org/zerock/myapp/service/FarmServiceTests.java
src/test/java/org/zerock/myapp/service/ProductServiceTests.java

별이 4/17 오전 업데이트

---

src/main/java/org/zerock/myapp/controller/HpCheckController.java
src/main/webapp/WEB-INF/views/signup/agreement.jsp
src/main/webapp/WEB-INF/views/signup/info.jsp
src/main/webapp/resources/signup/css/info.css
src/main/webapp/resources/signup/js/info.js

info.jsp 
info.js
info.css
HpCheckController.java 
수정 완료
확인 부탁

[혁규] 회원가입 코드 수정, 추가2

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/java/org/zerock/myapp/domain/LoginDTO.java
src/main/java/org/zerock/myapp/service/MemberService.java
src/main/java/org/zerock/myapp/service/MemberServiceImpl.java
src/main/resources/mybatis-config.xml
src/main/resources/org/zerock/myapp/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/login/Login_Main.jsp
src/main/webapp/resources/js/login/Login_Main.js

id랑 password 값 입력 후 로그인하기 버튼 클릭 시 DB에 있는 회원 정보는 받아오는데 이후에 errorpage로 연동되는 현상이 발생해서 오류 해결 중입니다 8ㅅ8

[셍나] 로그인 컨트롤러, MemberMapper.xml 로그인 파트 수정 중

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/java/org/zerock/myapp/domain/LoginDTO.java
src/main/resources/log4j2.xml

혁규 PR 받고 머지 이후 테스트 겸 로그인 코드 수정 중입니당 ㅇ_<

[셍나] 로그인 버튼 클릭 이후 에러 발생 코드 수정 중

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/java/org/zerock/myapp/domain/LoginDTO.java
src/main/java/org/zerock/myapp/service/MemberService.java
src/main/java/org/zerock/myapp/service/MemberServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/login/Login_Main.jsp

[셍나] 로그인 성공 시 에러 페이지 발생함. 수정 중..

---

src/main/resources/org/zerock/myapp/mapper/MemberMapper.xml

OrderController, MemberMapper, Order.jsp 수정 중.. 미완..!

[찬돌] OrderController, MemberMapper, Order.jsp 수정중 입니다

---

src/main/webapp/WEB-INF/views/signup/info.jsp
src/main/webapp/resources/js/signup/signup_info.js

info.jsp
info.js 
수정 
유효성 검사 수정 
가입 시 입력 값 검증 수정

[혁규] 회원가입 수정 

---

pom.xml
src/main/java/org/zerock/myapp/controller/AdminController.java
src/main/java/org/zerock/myapp/controller/ProductContoller.java
src/main/java/org/zerock/myapp/domain/AttachImageVO.java
src/main/webapp/WEB-INF/views/admin/product/register.jsp
src/main/webapp/WEB-INF/web.xml
src/main/webapp/resources/js/admin/register.js

별이 4/18 오전 업데이트

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/webapp/WEB-INF/views/main.jsp

흑흑 드디어 ㅠ-ㅠ!!! 
관리자, 일반 회원 둘 다 로그인 가능!
메인 페이지로 이동 시 주소 /login/main 남아있던 거 수정 완료!

[셍나] 로그인(관리자, 일반) 기능 추가 완료!

---

src/main/webapp/WEB-INF/views/admin/product/register.jsp

[별이] 4/18 오후 업데이트 - register.jsp / 오류난다해서 업데이트해봄

[별이] 4/18 오후 업데이트 - register.jsp / 오류난다해서 업데이트해봄

---

pom.xml
src/main/java/org/zerock/myapp/controller/LoginController.java

[셍나] 로그인 파트 비밀번호 암호화 진행 중 

---

src/main/webapp/META-INF/maven/org.zerock/MYMG/pom.xml
src/test/java/org/zerock/myapp/mapper/EmailCheckMapperTests.java
src/test/java/org/zerock/myapp/mapper/HpCheckMapperTests.java

IdCheck
HpCheck
EmailCheck 
test 클래스 추가

[혁규] mapper test 클래스 추가

---

src/main/webapp/WEB-INF/spring/appServlet/security-context.xml

[셍나] 로그인 비밀번호 암호화 진행 중

---

src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

[셍나] PR받은 파일들 충돌 해결 완료

---

src/main/java/org/zerock/myapp/controller/KakaoController.java
src/main/java/org/zerock/myapp/domain/TodoDTO.java
src/main/java/org/zerock/myapp/domain/accountDAO.java
src/main/java/org/zerock/myapp/service/KakaoService.java
src/main/java/org/zerock/myapp/service/KakaoServiceImpl.java
src/main/webapp/WEB-INF/spring/appServlet/security-context.xml
src/main/webapp/WEB-INF/views/signup/main.jsp

controller 
service
serviceImpl 추가 및 수정

[혁규] 카카오 소셜 로그인 구현중

---

pom.xml
src/main/java/org/zerock/myapp/domain/OrderPageItemDTO.java
src/main/webapp/META-INF/maven/org.zerock/MYMG/pom.xml
src/main/webapp/WEB-INF/views/order/order.jsp
src/main/webapp/resources/css/order/order.css
src/main/webapp/resources/js/order/order.js

1. dependency 결제api 추가
2.  OrderPageItemDTO 수정
3.  order.jsp,js,css 수정중

[찬돌] order.jsp,js,css 수정중 + OrderPageItemDTO 수정 => 결제금액 출력

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/webapp/WEB-INF/views/main.jsp

1. LoginController에 로그아웃 메소드 추가
2. main.jsp에 로그아웃 GET방식 매핑 수정

[셍나] 로그아웃 기능 추가 완료 - 세션 제거 시 'member' 세션 제거로 구현

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/java/org/zerock/myapp/controller/SignupController.java
src/main/webapp/WEB-INF/views/cart.jsp
src/main/webapp/WEB-INF/views/common/footer.jsp
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/userInfo.jsp
src/main/webapp/resources/js/main.js
src/main/webapp/resources/main/js/main.js

1. LoginController 수정
2. main.js에 비동기식 로그아웃 ajax 수정
3. 테스트 위해서 cart랑 userinfo 등등 매핑이랑 여러개 수정함.. 머였을까..?

[셍나] 비동기식 로그아웃 방식 구현 (jsp에서 js 불러올 때 body 태그 하단에 위치시켜야지만 가능함 -> 수정 필요)

---

pom.xml
src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/webapp/WEB-INF/spring/appServlet/security-context.xml
src/main/webapp/WEB-INF/views/login/Login_Find_ID.jsp
src/main/webapp/WEB-INF/views/login/Login_Main.jsp
src/main/webapp/WEB-INF/web.xml
src/main/webapp/resources/css/login/Login_Find_ID.css
src/main/webapp/resources/js/main.js

[셍나] 아이디 찾기 기능 구현 중 (Login_Find_ID.jsp 랑 css 추가)

---

src/main/java/org/zerock/myapp/controller/KakaoController.java
src/main/java/org/zerock/myapp/domain/SocialMemberDTO.java
src/main/java/org/zerock/myapp/domain/SocialMemberVO.java
src/main/java/org/zerock/myapp/service/KakaoService.java
src/main/java/org/zerock/myapp/service/KakaoServiceImpl.java
src/main/webapp/WEB-INF/views/signup/complete.jsp
src/main/webapp/resources/css/signup/signup_complete.css
src/main/webapp/resources/js/signup/signup_info.js

controller 
service 수정 및 추가 
info.js  중복 에러 해결중
complete.js  로그인 화면으로 이동 수정

[혁규] 카카오 로그인 서비스 수정

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/webapp/WEB-INF/views/login/Login_Change_PW.jsp
src/main/webapp/WEB-INF/views/login/Login_Main.jsp
src/main/webapp/resources/css/login/Login_Change_PW.css
src/main/webapp/resources/js/login/Login_Change_PW.js
src/main/webapp/resources/js/login/Login_Find_ID.js

프론트 작업이랑 뷰 작업만 했고 아직 기능 구현은 안되어 있어요 !!!!

[셍나] 아이디 찾기 및 비밀번호 변경을 위한 jsp, css, js 작업 중! 현재 단순 해당 페이지로 이동 가능

---

src/main/webapp/WEB-INF/views/login/Login_Find_ID.jsp
src/main/webapp/WEB-INF/views/login/Login_Main.jsp
src/main/webapp/resources/css/login/Login_Change_PW.css
src/main/webapp/resources/css/login/Login_Find_ID.css
src/main/webapp/resources/css/login/Login_Main.css
src/main/webapp/resources/js/login/Login_Change_PW.js
src/main/webapp/resources/js/login/Login_Find_ID.js

아이디 찾기, 비밀번호 변경 부분이 자꾸 내려가서 조절 중이에여 ~~

[셍나] 프론트 작업 중 - 로그인 메인 창 비율 조절 중

---

src/main/java/org/zerock/myapp/domain/OrderPageItemDTO.java
src/main/webapp/WEB-INF/views/order/order.jsp
src/main/webapp/resources/css/order/order.css

[찬돌] OrderPageItemDTO 일부수정, order.jsp/css 수정2

[찬돌] OrderPageItemDTO 일부수정, order.jsp/css 수정2

---

src/main/java/org/zerock/myapp/controller/HpCheckController.java
src/main/java/org/zerock/myapp/controller/KakaoController.java
src/main/java/org/zerock/myapp/service/HpCheckServiceImpl.java

[혁규] 휴대폰 인증 관련 매핑 수정

---

src/main/java/org/zerock/myapp/controller/AdminController.java
src/main/java/org/zerock/myapp/controller/FaqController.java
src/main/java/org/zerock/myapp/controller/HelpController.java
src/main/java/org/zerock/myapp/controller/MainController.java
src/main/java/org/zerock/myapp/domain/ProductDTO.java
src/main/java/org/zerock/myapp/utils/FileUploadUtils.java
src/main/resources/org/zerock/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
src/main/webapp/WEB-INF/spring/root-context.xml
src/main/webapp/WEB-INF/views/admin/faq/list.jsp
src/main/webapp/WEB-INF/views/help/faq.jsp
src/main/webapp/WEB-INF/views/help/get.jsp
src/main/webapp/WEB-INF/views/help/guide.jsp
src/main/webapp/WEB-INF/views/help/main.jsp
src/main/webapp/WEB-INF/views/help/notice.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/resources/css/help/faq.css
src/main/webapp/resources/css/help/get.css
src/main/webapp/resources/css/help/main.css
src/main/webapp/resources/css/help/notice.css

servlet-context.xml, root-context.xml 수정
-파일업로드 루트 추가
product VO, DTO, productMapper.xml 수정
-썸네일용 필드 추가 main_image2
패키지 추가 org.zerock.myapp.utils
파일업로드용 클래스 추가 FileUploadUtils
AdminController 수정
------------------------
고객센터
MainController
-고객센터 help/main 추가
고객센터 jsp 추가
-main.jsp
-notice.jsp
-faq.jsp
-guide.jsp
HelpController
-고객센터 help/faq, help/notice, help/guide 추가

[별이]고객센터(faq, notice, 이용약관) 메인페이지와 연결

---

src/main/java/org/zerock/myapp/controller/KakaoController.java
src/main/java/org/zerock/myapp/domain/SocialMemberDTO.java
src/main/java/org/zerock/myapp/domain/SocialMemberVO.java
src/main/java/org/zerock/myapp/service/KakaoServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/SocialMemberMapper.xml

socialmembermapper.xml
socialmemberDTO 수정
및 오류테스트

[혁규] 카카오 소셜 회원가입 구현

---

src/main/resources/org/zerock/myapp/mapper/NoticeMapper.xml
src/main/webapp/WEB-INF/views/help/faq.jsp
src/main/webapp/WEB-INF/views/help/get.jsp
src/main/webapp/WEB-INF/views/help/guide.jsp
src/main/webapp/WEB-INF/views/help/notice.jsp
src/main/webapp/resources/css/help/get.css
src/main/webapp/resources/css/help/guide.css
src/main/webapp/resources/css/help/notice.css

고객센터 - 이용안내(guide) 수정 완료
-guide.jsp
-gitde.css
나머지 내역은 크게 수정한 거 없음

[별이] 4/24 고객센터 - 이용안내(guide) 수정 완료

---

src/main/java/org/zerock/myapp/controller/UserInfoController.java
src/main/java/org/zerock/myapp/service/MsgSendServiceImpl.java
src/main/webapp/WEB-INF/views/userInfo.jsp
src/main/webapp/resources/js/userInfo.js

[채영]비밀번호 확인 구현 중(04/24)

---

src/main/resources/org/zerock/myapp/mapper/SocialMemberMapper.xml

[혁규] 카카오 회원가입 수정

---

src/main/java/org/zerock/myapp/controller/UserInfoController.java
src/main/java/org/zerock/myapp/service/MsgSendServiceImpl.java
src/main/webapp/WEB-INF/views/userInfo.jsp

[채영] 비밀번호 확인 성공 (04/24)

---

src/main/java/org/zerock/myapp/controller/OrderController.java
src/main/java/org/zerock/myapp/domain/OrderDTO.java
src/main/java/org/zerock/myapp/domain/OrderItemDTO.java
src/main/java/org/zerock/myapp/domain/OrderPageDTO.java
src/main/java/org/zerock/myapp/domain/OrderPageItemDTO.java
src/main/java/org/zerock/myapp/mapper/OrderMapper.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/OrderMapper.xml
src/main/webapp/WEB-INF/views/order/order.jsp
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

1. OrderMapper에 메서드 추가
2. OrderMapper.xml에 메서드 쿼리문 추가
3. OrderDTO 필드 일부 수정
4. OrderItemDTO 필드 일부 수정
5. OrderMapperTests 작업중

[찬돌] OrderMapper,OrderMapper.xml 추가, OrderMapperTests 수행중

---

src/main/java/org/zerock/myapp/domain/OrderDTO.java
src/main/java/org/zerock/myapp/domain/OrderItemDTO.java
src/main/java/org/zerock/myapp/mapper/OrderMapper.java
src/main/java/org/zerock/myapp/service/OrderService.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/OrderMapper.xml
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

1. OrderDTO 필드명 수정
2. OrderItemDTO 필드명 수정
3. OrderMapper 수정
4. OrderMapperTests 수정
5. OrderService 수정
6. OrderServiceImpl 수정

[찬돌] order정보 DB에 저장로직 구현중, OrderService,OrderServiceImpl

---

src/main/java/org/zerock/myapp/controller/KakaoController.java
src/main/java/org/zerock/myapp/controller/SignupController.java
src/main/java/org/zerock/myapp/mapper/SocialMemberMapper.java
src/main/webapp/META-INF/maven/org.zerock/MYMG/pom.xml
src/main/webapp/resources/js/signup/signup_info.js

kakaoController 수정 및 자잘한 부분 수정

[혁규] 소셜 회원가입 / 로그인 처리 구현

---

src/main/resources/org/zerock/myapp/mapper/SocialMemberMapper.xml
src/main/webapp/WEB-INF/views/signup/addinfo.jsp
src/main/webapp/WEB-INF/views/signup/info.jsp
src/main/webapp/resources/css/signup/signup_addinfo.css
src/main/webapp/resources/css/signup/signup_info.css
src/main/webapp/resources/js/signup/signup_addinfo.js
src/main/webapp/resources/js/signup/signup_info.js

addinfo.jsp
signup_addinfo.css
signup_addinfo.js
socialMemberMapper.xml 수정

[혁규] 소셜 추가정보 입력 수정

---

src/main/java/org/zerock/myapp/controller/OrderController.java
src/main/java/org/zerock/myapp/mapper/CartMapper.java
src/main/java/org/zerock/myapp/mapper/MemberMapper.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/CartMapper.xml
src/main/resources/org/zerock/myapp/mapper/MemberMapper.xml
src/main/webapp/META-INF/maven/org.zerock/MYMG/pom.xml
src/test/java/org/zerock/myapp/mapper/CartMapperTests.java
src/test/java/org/zerock/myapp/mapper/MemberMapperTests.java
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

[찬돌] order정보 DB에 저장로직 구현중, OrderService,OrderServiceImpl 2 4/26

[찬돌] order정보 DB에 저장로직 구현중, OrderService,OrderServiceImpl 2 4/26

---

src/main/webapp/WEB-INF/web.xml

web.xml에 기존 설정 안지워서 서버가 안돌아갔네여 ㅠㅠ

[셍나] 이메일 인증 관련 설정 파일 오류 나서 수정해서 재업!!

---

src/main/java/org/zerock/myapp/controller/OrderController.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/MemberMapper.xml
src/main/resources/org/zerock/myapp/mapper/OrderMapper.xml
src/main/webapp/META-INF/maven/org.zerock/MYMG/pom.xml
src/main/webapp/WEB-INF/views/order/order.jsp
src/test/java/org/zerock/myapp/mapper/CartMapperTests.java
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

[찬돌] order페이지 고치는중...ㅠㅠ

---

src/main/webapp/META-INF/maven/org.zerock/MYMG/pom.xml
src/main/webapp/resources/js/signup/signup_info.js
src/test/java/org/zerock/myapp/mapper/SocialMapperTests.java

info.js  유효성 검사 수정
socialMapperTests 추가

[혁규] 소셜 테스트 추가  및 유효성 검사 수정

---

src/main/java/org/zerock/myapp/controller/MemberController.java
src/main/webapp/WEB-INF/views/login/Login_Find_ID.jsp
src/main/webapp/resources/js/login/Login_Find_ID.js
src/test/java/org/zerock/myapp/controller/MemberControllerTests.java

1. MemberController.java 수정
2. Login_Find_ID.jsp랑 js 수정 (이메일 인증 위해서 ajax 코드 추가, 디자인 조금 수정)
3. MemberControllerTests.java 주석 수정

[셍나] 아이디 찾기 - 이메일 인증 구현 완료 (프론트 수정은 나중에!)

---

src/main/java/org/zerock/myapp/controller/OrderController.java
src/main/resources/org/zerock/myapp/mapper/OrderMapper.xml
src/main/webapp/WEB-INF/views/order/order.jsp
src/main/webapp/resources/css/order/order.css
src/main/webapp/resources/js/order/order.js
src/test/java/org/zerock/myapp/controller/MemberControllerTests.java
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

[찬돌] order페이지에서 주문하기 클릭시 DB에 MYMG_ORDER테이블에 저장완료 >_-
Can’t automatically merge. Don’t worry, you can still create the pull request. 이게 뭐죱

[찬돌] order페이지에서 주문하기 클릭시 DB에 MYMG_ORDER테이블에 저장완료 >_-

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/java/org/zerock/myapp/controller/MemberController.java
src/main/java/org/zerock/myapp/mapper/MemberMapper.java
src/main/java/org/zerock/myapp/service/MemberService.java
src/main/java/org/zerock/myapp/service/MemberServiceImpl.java
src/main/java/org/zerock/myapp/service/MsgSendServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/MemberMapper.xml
src/main/webapp/resources/js/login/Login_Change_PW.js
src/main/webapp/resources/js/login/Login_Find_ID.js

이제 핸드폰 전송 방식 구현하면 될거 같아요 -ㅇ-!!!

[셍나] 비밀번호 변경 - 이메일 전송 방식 구현 완료

---

src/main/java/org/zerock/myapp/controller/LoginController.java
src/main/java/org/zerock/myapp/controller/MemberController.java
src/main/java/org/zerock/myapp/mapper/MemberMapper.java
src/main/java/org/zerock/myapp/service/MemberService.java
src/main/java/org/zerock/myapp/service/MemberServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/MemberMapper.xml
src/main/webapp/resources/js/login/Login_Change_PW.js
src/main/webapp/resources/js/login/Login_Find_ID.js

사실 아직 임시 비번 발송 버튼 클릭 이후 메인으로 밀어버리는거 안함 ^-^..b

[셍나] 로그인 - 비밀번호 변경 기능 구현 완료

---

src/main/java/org/zerock/myapp/controller/OrderController.java
src/main/java/org/zerock/myapp/domain/OrderDTO.java
src/main/java/org/zerock/myapp/domain/OrderItemDTO.java
src/main/java/org/zerock/myapp/domain/OrderPageItemDTO.java
src/main/java/org/zerock/myapp/mapper/OrderMapper.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/OrderMapper.xml
src/main/webapp/WEB-INF/views/cart.jsp
src/main/webapp/WEB-INF/views/order/order.jsp
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

[찬돌] 죽고싶어요.. ProductId가 order.jsp에 안들어가서 문제해결중..

[찬돌] 죽고싶어요.. ProductId가 order.jsp에 안들어가서 문제해결중..

---

src/main/java/org/zerock/myapp/controller/MainController.java
src/main/java/org/zerock/myapp/mapper/ProductMapper.java
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/product/list.jsp

main 페이지내에  navigation 상품 목록 링크 수정
1. mapper
- ProductMapper.java 
- 42번째 줄 수정
2. controller
- MainController.java
- 24, 28, 32, 61번째 줄 수정 및 추가
3. webapp / WEB-INF / view
-  main.jsp
- 92번째 줄 수정
4. webapp / WEB-INF / view / product
-  list.jsp
- 24번째 줄 삭제

[진호] 05/01 수정 사항 - 

---

src/main/java/org/zerock/myapp/controller/OrderController.java
src/main/java/org/zerock/myapp/domain/OrderDTO.java
src/main/java/org/zerock/myapp/domain/OrderItemDTO.java
src/main/java/org/zerock/myapp/mapper/OrderMapper.java
src/main/java/org/zerock/myapp/service/OrderService.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/OrderMapper.xml
src/main/webapp/WEB-INF/views/order/order.jsp
src/main/webapp/WEB-INF/views/order/orderSuccess.jsp
src/main/webapp/resources/js/order/order.js

[찬돌] orderSuccess db데이터 불러오기 완료

[찬돌] orderSuccess db데이터 불러오기 완료

---

pom.xml
src/main/java/org/zerock/myapp/api/NaverLoginApi.java
src/main/java/org/zerock/myapp/business/NaverBO.java
src/main/java/org/zerock/myapp/controller/NaverController.java
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
src/main/webapp/WEB-INF/spring/root-context.xml
src/main/webapp/WEB-INF/views/login/Login_Main.jsp

[셍나] 네이버 로그인 구현 중

---

src/main/java/org/zerock/myapp/domain/Page_ProductDTO.java
src/main/resources/org/zerock/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/product/info.jsp
src/main/webapp/resources/css/product/info.css
src/main/webapp/resources/css/product/list.css

1. header 수정
- common / header.jsp
2.  domain / Page_ProductDTO.java 수정
3.  mapper / ProductMapper.xml 수정
4. WEB-INF / views / product / info.jsp 수정
5. resources / product / list.css 수정
6. resources / product / info.css 수정

05/02 수정사항

---

src/main/webapp/WEB-INF/views/order/order.jsp
src/main/webapp/WEB-INF/views/order/orderSuccess.jsp
src/main/webapp/resources/js/order/order.js
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

 [찬돌] 결제API구현완료.. ajax수정 필요

---

src/main/java/org/zerock/myapp/controller/OrderController.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/webapp/WEB-INF/views/cart.jsp
src/main/webapp/WEB-INF/views/product/info.jsp
src/main/webapp/resources/js/order/order.js

[찬돌] 상품상세페이지에서 구매버튼 활성화 완료

---

src/main/java/org/zerock/myapp/controller/NaverController.java
src/main/java/org/zerock/myapp/mapper/SocialMemberMapper.java
src/main/java/org/zerock/myapp/service/SocialMemberService.java
src/main/resources/mybatis-config.xml
src/main/resources/org/zerock/myapp/mapper/SocialMemberMapper.xml

[셍나] 네이버 로그인 구현 완료

---

src/main/java/org/zerock/myapp/controller/NaverController.java
src/main/resources/org/zerock/myapp/mapper/SocialMemberMapper.xml

[셍나] SocialMemberMapper.xml 수정

---

src/main/java/org/zerock/myapp/domain/Page_ProductDTO.java
src/main/java/org/zerock/myapp/mapper/ProductMapper.java
src/main/resources/org/zerock/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/info.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/css/product/info.css
src/main/webapp/resources/css/product/list.css

ProductMapper.xml
ProductMapper.java
- SelectOrder, SelectAllList 쿼리문 수정
Page_ProductDTO.java
- 필드 추가
product / info.jsp 
product / list.jsp
product / css /  info.css
product / css /  list.css
- 수정

[진호] 수정사항 - 05/03

---

src/main/webapp/WEB-INF/views/order/orderSuccess.jsp
src/main/webapp/resources/css/order/orderSuccess.css
src/main/webapp/resources/js/login/Login_Find_ID.js

[찬돌] orderSuccess.jsp, css 완료

---

src/main/webapp/WEB-INF/views/product/info.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/css/product/info.css
src/main/webapp/resources/css/product/list.css

product / list.jsp
product / info.jsp
product / css / list.css
product / css / info.css
- 수정

[진호] 수정 사항 - 05/ 03(2)

---

src/main/java/org/zerock/myapp/controller/OrderDetailController.java
src/main/webapp/WEB-INF/views/order/orderDetail.jsp
src/main/webapp/resources/css/order/orderDetail.css

[찬돌] orderDetailController,jsp,css 틀 추가

[찬돌] orderDetailController,jsp,css 틀 추가

---

src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/webapp/WEB-INF/views/order/order.jsp
src/main/webapp/WEB-INF/views/product/info.jsp
src/main/webapp/resources/css/order/order.css

[찬돌] 재고차감 추가, 상세페이지 주문 복구

---

src/main/java/org/zerock/myapp/controller/ProductContoller.java
src/main/java/org/zerock/myapp/domain/Criteria.java
src/main/java/org/zerock/myapp/mapper/ProductMapper.java
src/main/resources/org/zerock/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/css/product/info.css
src/main/webapp/resources/css/product/list.css

productController.java
Criteria.java
ProductMapper.java
ProductMapper.xml
- 상품 개수(12개) 수정
list.jsp
info.css
list.css
- 색상 변경

[진호] 수정 사항 

---

src/main/java/org/zerock/myapp/controller/ProductContoller.java
src/main/java/org/zerock/myapp/domain/Criteria.java
src/main/resources/org/zerock/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/info.jsp
src/main/webapp/WEB-INF/views/product/list.jsp

1. domain / Criteria.java
- queryString 수정
1. ProductMapper.xml
2. Controller / ProductController.java
3. views / list.jsp
4. views / info.jsp
- 상단 링크 수정

[진호] 수정 사항 - 05/04

---

src/main/java/org/zerock/myapp/controller/QuestionController.java
src/main/java/org/zerock/myapp/domain/QuestionDTO.java
src/main/java/org/zerock/myapp/domain/QuestionVO.java
src/main/java/org/zerock/myapp/mapper/QuestionMapper.java
src/main/java/org/zerock/myapp/service/QuestionService.java
src/main/java/org/zerock/myapp/service/QuestionServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/QuestionMapper.xml
src/main/webapp/WEB-INF/views/help/faq.jsp
src/main/webapp/WEB-INF/views/help/get.jsp
src/main/webapp/WEB-INF/views/help/guide.jsp
src/main/webapp/WEB-INF/views/help/main.jsp
src/main/webapp/WEB-INF/views/help/notice.jsp
src/main/webapp/WEB-INF/views/help/question.jsp
src/main/webapp/WEB-INF/views/help/search.jsp
src/main/webapp/WEB-INF/views/help/search2.jsp
src/main/webapp/WEB-INF/views/help/write.jsp
src/main/webapp/resources/css/help/question.css
src/main/webapp/resources/css/help/write.css
src/main/webapp/resources/css/login/Login_Main.css
src/main/webapp/resources/js/signup/signup_info.js
src/test/java/org/zerock/myapp/mapper/QuestionMapperTests.java
src/test/java/org/zerock/myapp/service/QuestionServiceTests.java

게시판 등록 추가 
write.jsp
write.css
question.css
question.jsp
고객센터 내의 1:1문의 카테고리 추가

[혁규] 1:1문의 구현중

---

src/main/java/org/zerock/myapp/controller/MypageController.java
src/main/java/org/zerock/myapp/mapper/MypageMapper.java
src/main/java/org/zerock/myapp/service/MypageService.java
src/main/java/org/zerock/myapp/service/MypageServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/MypageMapper.xml
src/main/webapp/WEB-INF/views/mypage/OrderDetails.jsp
src/test/java/org/zerock/myapp/mapper/MypageMapperTests.java

[찬돌] 상품상세정보 상품명 가져오기 중

---

src/main/java/org/zerock/myapp/controller/MypageController.java
src/main/webapp/resources/css/mypage/OrderList.css

최신 주문 내역이 맨 위로 올 수 있도록 해야 할거 같은데 고민 중

[셍나] 주문 컨테이너 간격 조절

---

src/main/java/org/zerock/myapp/controller/QuestionController.java
src/main/java/org/zerock/myapp/mapper/QuestionMapper.java
src/main/java/org/zerock/myapp/service/QuestionService.java
src/main/java/org/zerock/myapp/service/QuestionServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/QuestionMapper.xml
src/main/webapp/WEB-INF/views/admin/common/header.jsp
src/main/webapp/WEB-INF/views/admin/question/list.jsp
src/main/webapp/WEB-INF/views/admin/question/modify.jsp
src/main/webapp/WEB-INF/views/admin/question/page.jsp
src/main/webapp/WEB-INF/views/admin/question/register.jsp
src/main/webapp/WEB-INF/views/help/question.jsp
src/main/webapp/WEB-INF/views/help/write.jsp
src/main/webapp/WEB-INF/views/signup/info.jsp
src/main/webapp/resources/css/admin/get2.css
src/main/webapp/resources/css/admin/list2.css
src/test/java/org/zerock/myapp/mapper/QuestionMapperTests.java
src/test/java/org/zerock/myapp/service/QuestionServiceTests.java

[혁규]1:1문의 관리자 페이지 조회 및 내용

---

src/main/webapp/resources/js/login/Login_Main.js

[셍나] 자동 로그인 기능 alert 삭제

---

src/main/java/org/zerock/myapp/controller/MypageController.java
src/main/java/org/zerock/myapp/mapper/MypageMapper.java
src/main/java/org/zerock/myapp/service/OrderService.java
src/main/java/org/zerock/myapp/service/OrderServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/MypageMapper.xml
src/main/webapp/WEB-INF/views/mypage/OrderDetails.jsp
src/test/java/org/zerock/myapp/mapper/MypageMapperTests.java
src/test/java/org/zerock/myapp/mapper/OrderMapperTests.java

[찬돌] 주문내역 수정중 2

---

src/main/java/org/zerock/myapp/controller/MypageController.java
src/main/resources/org/zerock/myapp/mapper/MypageMapper.xml
src/main/webapp/WEB-INF/views/mypage/OrderList.jsp

[찬돌] 주문내역 수정중 3

---

src/main/webapp/WEB-INF/views/mypage/OrderList.jsp

[찬돌] 주문내역 수정중 4

---

src/main/webapp/WEB-INF/views/mypage/OrderList.jsp
src/main/webapp/resources/css/mypage/OrderList.css

[셍나] 프론트 수정

---

src/main/java/org/zerock/myapp/controller/MypageController.java
src/main/webapp/WEB-INF/views/mypage/OrderList.jsp
src/main/webapp/resources/css/mypage/OrderList.css

[셍나] OrderDetails.jsp랑 OrderList.jsp aside바에 이름 불러올 수 있도록 mypage 컨트롤러 수정

---

src/main/java/org/zerock/myapp/controller/QuestionController.java
src/main/java/org/zerock/myapp/interceptor/QuestionInterceptor.java
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
src/main/webapp/WEB-INF/views/help/faq.jsp
src/main/webapp/WEB-INF/views/help/get.jsp
src/main/webapp/WEB-INF/views/help/guide.jsp
src/main/webapp/WEB-INF/views/help/main.jsp
src/main/webapp/WEB-INF/views/help/notice.jsp
src/main/webapp/WEB-INF/views/help/page.jsp
src/main/webapp/WEB-INF/views/help/question.jsp
src/main/webapp/WEB-INF/views/help/search.jsp
src/main/webapp/WEB-INF/views/help/search2.jsp
src/main/webapp/WEB-INF/views/help/write.jsp
src/main/webapp/WEB-INF/views/signup/main.jsp
src/main/webapp/resources/css/admin/get2.css
src/main/webapp/resources/css/signup/signup_main.css

[혁규] 1:1문의 로그인 세션 처리

---

src/main/resources/org/zerock/myapp/mapper/MypageMapper.xml

[셍나] 주문 내역 최신순으로 정렬하기 위해서 MypageMapper.xml 쿼리 수정

---

src/main/java/org/zerock/myapp/controller/AdminController.java
src/main/webapp/WEB-INF/views/admin/faq/get.jsp
src/main/webapp/WEB-INF/views/admin/faq/list.jsp
src/main/webapp/WEB-INF/views/admin/faq/modify.jsp
src/main/webapp/WEB-INF/views/admin/faq/register.jsp
src/main/webapp/WEB-INF/views/admin/faq/search.jsp
src/main/webapp/WEB-INF/views/admin/farm/get.jsp
src/main/webapp/WEB-INF/views/admin/farm/list.jsp
src/main/webapp/WEB-INF/views/admin/farm/modify.jsp
src/main/webapp/WEB-INF/views/admin/farm/register.jsp
src/main/webapp/WEB-INF/views/admin/farm/search.jsp
src/main/webapp/WEB-INF/views/admin/main.jsp
src/main/webapp/WEB-INF/views/admin/member/get.jsp
src/main/webapp/WEB-INF/views/admin/member/list.jsp
src/main/webapp/WEB-INF/views/admin/notice/get.jsp
src/main/webapp/WEB-INF/views/admin/notice/list.jsp
src/main/webapp/WEB-INF/views/admin/notice/modify.jsp
src/main/webapp/WEB-INF/views/admin/notice/register.jsp
src/main/webapp/WEB-INF/views/admin/notice/search.jsp
src/main/webapp/WEB-INF/views/admin/product/get.jsp
src/main/webapp/WEB-INF/views/admin/product/list.jsp
src/main/webapp/WEB-INF/views/admin/product/modify.jsp
src/main/webapp/WEB-INF/views/admin/product/register.jsp
src/main/webapp/WEB-INF/views/admin/question/list.jsp
src/main/webapp/WEB-INF/views/help/faq.jsp
src/main/webapp/resources/css/admin/main.css
src/main/webapp/resources/css/help/faq.css

관리자페이지 일부 JSP 코드 수정
-테스트란 글자 삭제...
-faq 이상한 패딩 현상 수정...

[별이] 5/8 커밋4 - 관리자페이지 일부 JSP 코드 수정

---

src/main/webapp/WEB-INF/views/help/notice.jsp
src/main/webapp/resources/css/admin/list.css
src/main/webapp/resources/css/admin/register.css

[별이] 5/8 커밋4 - 관리자페이지 검색창 수정

---

src/main/java/org/zerock/myapp/controller/AdminController.java
src/main/java/org/zerock/myapp/mapper/ProductSearchMapper.java
src/main/java/org/zerock/myapp/service/ProductSearchService.java
src/main/java/org/zerock/myapp/service/ProductSearchServiceImpl.java
src/main/resources/org/zerock/myapp/mapper/ProductSearchMapper.xml
src/main/webapp/WEB-INF/views/admin/product/search.jsp

[별이] 5/9 커밋
